# Generated by Django 4.2.4 on 2023-08-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
