# Generated by Django 4.2.4 on 2023-08-24 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0002_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='projectFromUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
