# Generated by Django 4.2.4 on 2023-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_rename_creator_follow_follower'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'property'), name='unique_follower_property_combination'),
        ),
    ]
