# Generated by Django 4.2.4 on 2023-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0004_follow_unique_follower_property_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='display_name',
            field=models.CharField(max_length=500),
        ),
    ]
