# Generated by Django 4.2.4 on 2023-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0005_property_name_alter_property_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.CharField(default='osm', max_length=20),
        ),
    ]
