# Generated by Django 4.2.4 on 2023-08-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0006_property_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=21),
        ),
        migrations.AlterField(
            model_name='property',
            name='lon',
            field=models.DecimalField(decimal_places=16, max_digits=21),
        ),
    ]
