# Generated by Django 4.2.4 on 2023-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0007_alter_property_lat_alter_property_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='addresstype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
