# Generated by Django 4.2.4 on 2023-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0008_property_addresstype_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='with_suggestions',
            field=models.BooleanField(default=False),
        ),
    ]
